/**
 * apps/api/src/__tests__/openapi-contract.test.ts
 *
 * Contract test on the apps/api REST surface — snapshots the OpenAPI 3.1
 * spec generated by @fastify/swagger so any unintentional change to the
 * API surface fails CI until explicitly accepted.
 *
 * ## Why this is the right contract test for THIS repo
 *
 * Per qmd-team-intent-kb-apt (Batch 6) — a Pact-tool install would be
 * the wrong fit for this monorepo. There is no service-to-service HTTP
 * boundary internally (apps/mcp-server imports @qmd-team-intent-kb/store
 * and curator in-process; everything else is TS-import + shared types).
 * The only HTTP surface is apps/api's REST endpoints, exposed for
 * eventual external consumers.
 *
 * Pact's protection (catching breaking changes across deployment
 * boundaries with different release cadences) doesn't apply when there
 * are no external consumers yet. But the apps/api surface still wants
 * stability — an SDK generator pointing at /openapi.json should not
 * see surprise schema changes between releases.
 *
 * This snapshot test gives that protection. Procedure:
 *
 *   1. Boot apps/api in-process via the existing buildApp pattern.
 *   2. GET /openapi.json.
 *   3. Snapshot the stable parts (paths, components.schemas, tags).
 *      Skip the volatile parts (info.version — bumped on every release).
 *
 * When a contributor intentionally changes the surface (adds a route,
 * tightens a schema), the test fails. They run `pnpm vitest run
 * apps/api/src/__tests__/openapi-contract.test.ts --update-snapshots`,
 * the snapshot file changes, and the diff becomes a code-review signal.
 *
 * Forward trigger: when an external consumer repo emerges and is
 * deployed independently, install pact-js and run consumer/provider
 * verification — tracked in the follow-up bd.
 */

import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import type { FastifyInstance } from 'fastify';
import type Database from 'better-sqlite3';
import { createTestDatabase } from '@qmd-team-intent-kb/store';
import { buildApp } from '../app.js';

interface OpenApiSpec {
  openapi: string;
  info: { title: string; version: string };
  paths: Record<string, unknown>;
  components?: {
    schemas?: Record<string, unknown>;
    securitySchemes?: Record<string, unknown>;
  };
  tags?: Array<{ name: string; description?: string }>;
}

describe('OpenAPI contract', () => {
  let db: Database.Database;
  let app: FastifyInstance;

  beforeEach(async () => {
    db = createTestDatabase();
    app = buildApp({ db, silent: true });
    await app.ready();
  });

  afterEach(async () => {
    await app.close();
    db.close();
  });

  it('publishes a stable apps/api surface (snapshot)', async () => {
    const res = await app.inject({ method: 'GET', url: '/openapi.json' });
    expect(res.statusCode).toBe(200);
    const spec = res.json<OpenApiSpec>();

    // Snapshot the structural parts of the spec — anything that an
    // external SDK generator or partner integration would key off.
    // Deliberately exclude `info.version` (bumped on every release —
    // not a contract change) and `info.title` (engineer-cosmetic).
    const contractSurface = {
      openapi: spec.openapi,
      // Route shape: every path + every HTTP method per path. We snapshot
      // sorted method lists so insertion order doesn't churn the diff.
      paths: Object.fromEntries(
        Object.entries(spec.paths)
          .sort(([a], [b]) => a.localeCompare(b))
          .map(([path, methodsObj]) => {
            const methods = Object.keys(methodsObj as Record<string, unknown>).sort();
            return [path, { methods }];
          }),
      ),
      // Schema shape: just the names. Full schemas would balloon the
      // snapshot and force engineers to re-bless on every internal field
      // shuffle. The route inventory + the schema inventory together
      // catch all the breaking changes that matter to a consumer.
      schemas: Object.keys(spec.components?.schemas ?? {}).sort(),
      securitySchemes: Object.keys(spec.components?.securitySchemes ?? {}).sort(),
      tags: (spec.tags ?? []).map((t) => t.name).sort(),
    };

    expect(contractSurface).toMatchSnapshot();
  });
});
